name = "LynxGallery"
uuid = "c09c367f-9223-4bea-9149-5f0eecb3c411"
authors = ["Jorge Brito <jorge.brito.json@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
