name: CI
on:
  - push
  - pull_request

jobs:
  readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x scripts/readme.sh && ./scripts/readme.sh
      - run: git remote set-url origin ${{ secrets.ssh }}
      - run: git add README.md && git commit -m "Updated README.md"
      - run: git push origin HEAD:master