name: CI
on:
  - push
  - pull_request

jobs:
  readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build README.md
        run: |
          chmod +x scripts/readme.sh
          ./scripts/readme.sh
      - name: Setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit changes
        run: |
          git add README.md && git commit -m "Updated README.md"
          git push origin HEAD:master